import { defineCommand } from "citty"
import pc from "picocolors"
import {
  readFileSync,
  writeFileSync,
  mkdirSync,
  existsSync,
  copyFileSync,
  readdirSync,
  statSync,
} from "node:fs"
import { join, dirname } from "node:path"
import { homedir } from "node:os"
import { fileURLToPath } from "node:url"
import { spawnSync } from "node:child_process"

const SKILL_NAMES = ["tc-discuss", "tc-research", "tc-research-idea"]

const TOML_SECTION = `
[mcp_servers.tickercode]
command = "tc"
args = ["mcp"]
env = { TICKERCODE_API_KEY = "$TICKERCODE_API_KEY" }
`.trim()

function upsertTomlSection(toml: string, sectionName: string, sectionBody: string): string {
  const escaped = sectionName.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
  const re = new RegExp(`\\n?\\[${escaped}\\][\\s\\S]*?(?=\\n\\[|\\s*$)`)
  const section = `[${sectionName}]\n${sectionBody.trim()}\n`
  if (re.test(toml)) {
    return toml.replace(re, `\n${section}`)
  }
  const sep =
    toml && !toml.endsWith("\n\n")
      ? toml.endsWith("\n")
        ? "\n"
        : "\n\n"
      : ""
  return toml + sep + section
}

function getSkillSourceRoot(): string {
  const here = dirname(fileURLToPath(import.meta.url))
  for (const candidate of [
    join(here, "..", "..", ".claude", "skills"),
    join(here, "..", ".claude", "skills"),
    join(here, "..", "..", "..", ".claude", "skills"),
  ]) {
    if (existsSync(candidate)) return candidate
  }
  throw new Error(
    `skill source not found near ${here}. Expected .claude/skills/ adjacent to the CLI package.`,
  )
}

function getPluginMarketplaceRoot(kind: "claude-code" | "codex"): string {
  const here = dirname(fileURLToPath(import.meta.url))
  for (const candidate of [
    join(here, "..", "..", "plugins", kind),
    join(here, "..", "plugins", kind),
    join(here, "..", "..", "..", "plugins", kind),
  ]) {
    if (existsSync(candidate)) return candidate
  }
  throw new Error(
    `plugin marketplace root not found near ${here}. Expected plugins/${kind}/ adjacent to the CLI package.`,
  )
}

function getSandboxMarketplaceRoot(name: "tc-claude-plugin" | "tc-codex-plugin"): string | undefined {
  const here = dirname(fileURLToPath(import.meta.url))
  for (const candidate of [
    join(here, "..", "..", "..", "sandbox", name),
    join(here, "..", "..", "sandbox", name),
    join(here, "..", "sandbox", name),
  ]) {
    if (existsSync(candidate)) return candidate
  }
  return undefined
}

function copyDirRecursive(src: string, dst: string): number {
  let count = 0
  if (!existsSync(dst)) mkdirSync(dst, { recursive: true })
  for (const entry of readdirSync(src)) {
    const s = join(src, entry)
    const d = join(dst, entry)
    if (statSync(s).isDirectory()) {
      count += copyDirRecursive(s, d)
    } else {
      copyFileSync(s, d)
      count++
    }
  }
  return count
}

function stripFrontmatter(md: string): string {
  if (!md.startsWith("---\n")) return md
  const end = md.indexOf("\n---\n", 4)
  if (end === -1) return md
  return md.slice(end + 5).trimStart()
}

function buildGeminiMd(skillSrcRoot: string): string {
  const TICKERCODE_BLOCK_START = "<!-- tickercode-skills-start -->"
  const TICKERCODE_BLOCK_END = "<!-- tickercode-skills-end -->"
  const intro = `${TICKERCODE_BLOCK_START}

# Tickercode Skills (auto-generated by \`tc setup gemini\`)

ticker-code.com の MCP server (\`mcp__tickercode__*\`) と組み合わせて使う指南書群。
ユーザーが日本株の銘柄やテーマについて尋ねた時、以下の方針で対応してください。

`
  const sections: string[] = [intro]
  for (const name of SKILL_NAMES) {
    const path = join(skillSrcRoot, name, "SKILL.md")
    if (!existsSync(path)) continue
    const body = stripFrontmatter(readFileSync(path, "utf8"))
    sections.push(`\n---\n\n## Skill: ${name}\n\n${body.trim()}\n`)
  }
  sections.push(`\n${TICKERCODE_BLOCK_END}\n`)
  return sections.join("")
}

function upsertGeminiMd(geminiMdPath: string, generated: string): "created" | "updated" | "appended" {
  const TICKERCODE_BLOCK_START = "<!-- tickercode-skills-start -->"
  const TICKERCODE_BLOCK_END = "<!-- tickercode-skills-end -->"
  const dir = dirname(geminiMdPath)
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
  if (!existsSync(geminiMdPath)) {
    writeFileSync(geminiMdPath, generated, "utf8")
    return "created"
  }
  const existing = readFileSync(geminiMdPath, "utf8")
  if (
    existing.includes(TICKERCODE_BLOCK_START) &&
    existing.includes(TICKERCODE_BLOCK_END)
  ) {
    const before = existing.slice(0, existing.indexOf(TICKERCODE_BLOCK_START))
    const after = existing.slice(
      existing.indexOf(TICKERCODE_BLOCK_END) + TICKERCODE_BLOCK_END.length,
    )
    writeFileSync(geminiMdPath, before + generated + after, "utf8")
    return "updated"
  }
  const sep =
    existing && !existing.endsWith("\n\n")
      ? existing.endsWith("\n")
        ? "\n"
        : "\n\n"
      : ""
  writeFileSync(geminiMdPath, existing + sep + generated, "utf8")
  return "appended"
}

function upsertJsonMcpServer(
  settingsPath: string,
  serverName: string,
  serverConfig: Record<string, unknown>,
  force: boolean,
): "created" | "updated" | "skipped" | "added" {
  const dir = dirname(settingsPath)
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
  let parsed: Record<string, unknown> = {}
  if (existsSync(settingsPath)) {
    try {
      const raw = readFileSync(settingsPath, "utf8").trim()
      parsed = raw ? (JSON.parse(raw) as Record<string, unknown>) : {}
    } catch (err) {
      throw new Error(
        `${settingsPath} のパースに失敗しました: ${(err as Error).message}`,
      )
    }
  }
  const mcpServers =
    (parsed.mcpServers as Record<string, unknown> | undefined) ?? {}
  const existed = serverName in mcpServers
  if (existed && !force) return "skipped"
  mcpServers[serverName] = serverConfig
  parsed.mcpServers = mcpServers
  writeFileSync(settingsPath, JSON.stringify(parsed, null, 2) + "\n", "utf8")
  if (!existsSync(settingsPath)) return "created"
  return existed ? "updated" : "added"
}

function upsertCodexPluginConfig(
  configPath: string,
  marketplacePath: string,
  force: boolean,
): "updated" | "skipped" | "added" {
  const configDir = dirname(configPath)
  if (!existsSync(configDir)) mkdirSync(configDir, { recursive: true })
  const existingToml = existsSync(configPath)
    ? readFileSync(configPath, "utf8")
    : ""
  const hasMarketplace = existingToml.includes("[marketplaces.tickercode]")
  const hasPlugin = existingToml.includes('[plugins."tickercode@tickercode"]')
  if (hasMarketplace && hasPlugin && !force) return "skipped"

  let nextToml = upsertTomlSection(
    existingToml,
    "marketplaces.tickercode",
    `source_type = "local"\nsource = ${JSON.stringify(marketplacePath)}`,
  )
  nextToml = upsertTomlSection(
    nextToml,
    'plugins."tickercode@tickercode"',
    "enabled = true",
  )
  writeFileSync(configPath, nextToml, "utf8")
  return hasMarketplace || hasPlugin ? "updated" : "added"
}

function runLoggedCommand(command: string, args: string[]): void {
  process.stdout.write(pc.dim(`  $ ${command} ${args.join(" ")}\n`))
  const result = spawnSync(command, args, {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  })
  if (result.stdout) process.stdout.write(result.stdout)
  if (result.stderr) process.stderr.write(result.stderr)
  if (result.error) {
    throw result.error
  }
  if (result.status !== 0) {
    throw new Error(`${command} ${args.join(" ")} failed with exit code ${result.status}`)
  }
}

const codexCommand = defineCommand({
  meta: {
    name: "codex",
    description: "Setup tickercode skills + MCP server for Codex CLI",
  },
  args: {
    "skills-dir": {
      type: "string",
      description: "Where to copy skill bundles (default: ~/.agents/skills)",
    },
    "config-path": {
      type: "string",
      description: "Codex config TOML path (default: ~/.codex/config.toml)",
    },
    plugin: {
      type: "boolean",
      description: "Register the local Codex plugin marketplace and enable tickercode@tickercode",
      default: false,
    },
    "marketplace-path": {
      type: "string",
      description: "Codex plugin marketplace root (default: packaged plugins/codex)",
    },
    force: {
      type: "boolean",
      description: "Overwrite existing [mcp_servers.tickercode] section",
      default: false,
    },
  },
  async run({ args }) {
    const skillsDir = args["skills-dir"]
      ? String(args["skills-dir"])
      : join(homedir(), ".agents", "skills")
    const configPath = args["config-path"]
      ? String(args["config-path"])
      : join(homedir(), ".codex", "config.toml")
    const marketplacePath = args["marketplace-path"]
      ? String(args["marketplace-path"])
      : (getSandboxMarketplaceRoot("tc-codex-plugin") ?? getPluginMarketplaceRoot("codex"))

    process.stdout.write(pc.bold("Setting up tickercode for Codex CLI…\n"))

    if (args.plugin) {
      const action = upsertCodexPluginConfig(
        configPath,
        marketplacePath,
        Boolean(args.force),
      )
      if (action === "skipped") {
        process.stdout.write(
          pc.dim(`  - ${configPath} に plugin marketplace 既存、skip（--force で上書き）\n`),
        )
      } else {
        const verb = action === "updated" ? "の plugin marketplace を更新" : "に plugin marketplace を追記"
        process.stdout.write(`  ${pc.green("✓")} ${configPath} ${verb}\n`)
      }
    }

    // 1. config.toml: append [mcp_servers.tickercode]
    const configDir = dirname(configPath)
    if (!existsSync(configDir)) mkdirSync(configDir, { recursive: true })
    const existingToml = existsSync(configPath)
      ? readFileSync(configPath, "utf8")
      : ""
    const hasSection = existingToml.includes("[mcp_servers.tickercode]")
    if (hasSection && !args.force) {
      process.stdout.write(
        pc.dim(`  - ${configPath} に既存、skip（--force で上書き）\n`),
      )
    } else if (hasSection && args.force) {
      const replaced = existingToml.replace(
        /\[mcp_servers\.tickercode\][\s\S]*?(?=\n\[|$)/,
        `${TOML_SECTION}\n`,
      )
      writeFileSync(configPath, replaced, "utf8")
      process.stdout.write(`  ${pc.green("✓")} ${configPath} の既存セクションを更新\n`)
    } else {
      const sep =
        existingToml && !existingToml.endsWith("\n\n")
          ? existingToml.endsWith("\n")
            ? "\n"
            : "\n\n"
          : ""
      const newToml = existingToml + sep + TOML_SECTION + "\n"
      writeFileSync(configPath, newToml, "utf8")
      process.stdout.write(
        `  ${pc.green("✓")} ${configPath} に MCP server 設定を追記\n`,
      )
    }

    // 2. Copy skills to ~/.agents/skills/
    const skillSrcRoot = getSkillSourceRoot()
    let totalCopied = 0
    for (const name of SKILL_NAMES) {
      const src = join(skillSrcRoot, name)
      const dst = join(skillsDir, name)
      if (!existsSync(src)) {
        process.stdout.write(pc.dim(`  - ${name}: source not found, skip\n`))
        continue
      }
      const n = copyDirRecursive(src, dst)
      totalCopied += n
      process.stdout.write(
        `  ${pc.green("✓")} ${name} → ${dst} (${n} files)\n`,
      )
    }

    process.stdout.write(`\n${pc.bold("完了")}: ${totalCopied} files copied\n`)
    process.stdout.write(
      pc.dim(`  - tc auth login（未実行なら）で API key を設定\n`),
    )
    process.stdout.write(
      pc.dim(`  - codex を起動し「6594 のディスカッション」と打ってみる\n`),
    )
  },
})

const geminiCommand = defineCommand({
  meta: {
    name: "gemini",
    description: "Setup tickercode MCP + GEMINI.md for Gemini CLI",
  },
  args: {
    "settings-path": {
      type: "string",
      description: "Gemini settings.json path (default: ~/.gemini/settings.json)",
    },
    "gemini-md-path": {
      type: "string",
      description: "GEMINI.md path (default: ~/.gemini/GEMINI.md)",
    },
    force: {
      type: "boolean",
      description: "Overwrite existing tickercode entry / GEMINI.md block",
      default: false,
    },
  },
  async run({ args }) {
    const settingsPath = args["settings-path"]
      ? String(args["settings-path"])
      : join(homedir(), ".gemini", "settings.json")
    const geminiMdPath = args["gemini-md-path"]
      ? String(args["gemini-md-path"])
      : join(homedir(), ".gemini", "GEMINI.md")

    process.stdout.write(pc.bold("Setting up tickercode for Gemini CLI…\n"))

    // 1. settings.json: upsert mcpServers.tickercode
    const action = upsertJsonMcpServer(
      settingsPath,
      "tickercode",
      {
        command: "tc",
        args: ["mcp"],
        env: { TICKERCODE_API_KEY: "$TICKERCODE_API_KEY" },
      },
      Boolean(args.force),
    )
    if (action === "skipped") {
      process.stdout.write(
        pc.dim(`  - ${settingsPath} に既存、skip（--force で上書き）\n`),
      )
    } else {
      const verb =
        action === "updated" ? "の既存エントリを更新" : "に MCP server 設定を追記"
      process.stdout.write(`  ${pc.green("✓")} ${settingsPath} ${verb}\n`)
    }

    // 2. GEMINI.md: flatten skill content into single instruction file
    const skillSrcRoot = getSkillSourceRoot()
    const generated = buildGeminiMd(skillSrcRoot)
    const mdAction = upsertGeminiMd(geminiMdPath, generated)
    const mdVerb =
      mdAction === "created"
        ? "を新規作成"
        : mdAction === "updated"
          ? "の tickercode ブロックを更新"
          : "に tickercode ブロックを追記"
    process.stdout.write(`  ${pc.green("✓")} ${geminiMdPath} ${mdVerb}\n`)

    process.stdout.write(`\n${pc.bold("完了")}\n`)
    process.stdout.write(
      pc.dim(`  - tc auth login（未実行なら）で API key を設定\n`),
    )
    process.stdout.write(
      pc.dim(`  - gemini を起動し「6594 のディスカッション」と打ってみる\n`),
    )
  },
})

const claudeCommand = defineCommand({
  meta: {
    name: "claude",
    description: "Setup tickercode plugin for Claude Code",
  },
  args: {
    "marketplace-path": {
      type: "string",
      description:
        "Claude Code marketplace root (default: packaged plugins/claude-code)",
    },
    install: {
      type: "boolean",
      description: "Run Claude Code plugin marketplace add + plugin install",
      default: false,
    },
    scope: {
      type: "string",
      description: "Claude Code plugin install scope: user, project, or local (default: user)",
      default: "user",
    },
  },
  async run({ args }) {
    const marketplacePath = args["marketplace-path"]
      ? String(args["marketplace-path"])
      : (getSandboxMarketplaceRoot("tc-claude-plugin") ?? getPluginMarketplaceRoot("claude-code"))
    const scope = String(args.scope ?? "user")

    process.stdout.write(pc.bold("Setting up tickercode for Claude Code…\n"))
    if (args.install) {
      process.stdout.write(pc.dim("Installing via Claude Code plugin CLI.\n\n"))
      runLoggedCommand("claude", ["plugin", "validate", marketplacePath])
      runLoggedCommand("claude", [
        "plugin",
        "marketplace",
        "add",
        "--scope",
        scope,
        marketplacePath,
      ])
      runLoggedCommand("claude", [
        "plugin",
        "install",
        "--scope",
        scope,
        "tickercode@tickercode",
      ])
      process.stdout.write(`\n${pc.bold("完了")}: tickercode@tickercode installed (${scope})\n`)
      process.stdout.write(pc.dim("  - Claude Code を再起動、または /reload-plugins を実行\n"))
      process.stdout.write(pc.dim("  - /mcp で plugin:tickercode:tickercode が Connected か確認\n"))
      return
    }

    process.stdout.write(
      pc.dim("Claude Code plugins are installed from inside Claude Code.\n\n"),
    )
    process.stdout.write("Run this command from a shell:\n\n")
    process.stdout.write(`${pc.cyan(`tc setup claude --install --marketplace-path ${marketplacePath}`)}\n\n`)
    process.stdout.write("Or run these commands in Claude Code:\n\n")
    process.stdout.write(`${pc.cyan(`/plugin marketplace add ${marketplacePath}`)}\n`)
    process.stdout.write(`${pc.cyan(`/plugin install tickercode@tickercode`)}\n`)
    process.stdout.write(`${pc.cyan("/reload-plugins")}\n\n`)
    process.stdout.write(pc.bold("After install:\n"))
    process.stdout.write(pc.dim("  - tc auth login（未実行なら）で API key を設定\n"))
    process.stdout.write(pc.dim("  - /mcp で tickercode が listed されるか確認\n"))
    process.stdout.write(
      pc.dim("  - 「6594 の投資観点を分析して」と打って動作確認\n"),
    )
  },
})

export const setupCommand = defineCommand({
  meta: {
    name: "setup",
    description: "Setup tickercode for various CLI clients (claude / codex / gemini)",
  },
  subCommands: {
    claude: claudeCommand,
    codex: codexCommand,
    gemini: geminiCommand,
  },
})
