import { defineCommand } from "citty"
import pc from "picocolors"
import {
  readFileSync,
  writeFileSync,
  mkdirSync,
  existsSync,
  copyFileSync,
  readdirSync,
  statSync,
} from "node:fs"
import { join, dirname } from "node:path"
import { homedir } from "node:os"
import { fileURLToPath } from "node:url"

const SKILL_NAMES = ["tc-discuss", "tc-research", "tc-research-idea"]

const TOML_SECTION = `
[mcp_servers.tickercode]
command = "tc"
args = ["mcp"]
env = { TICKERCODE_API_KEY = "$TICKERCODE_API_KEY" }
`.trim()

function getSkillSourceRoot(): string {
  const here = dirname(fileURLToPath(import.meta.url))
  for (const candidate of [
    join(here, "..", "..", ".claude", "skills"),
    join(here, "..", ".claude", "skills"),
    join(here, "..", "..", "..", ".claude", "skills"),
  ]) {
    if (existsSync(candidate)) return candidate
  }
  throw new Error(
    `skill source not found near ${here}. Expected .claude/skills/ adjacent to the CLI package.`,
  )
}

function copyDirRecursive(src: string, dst: string): number {
  let count = 0
  if (!existsSync(dst)) mkdirSync(dst, { recursive: true })
  for (const entry of readdirSync(src)) {
    const s = join(src, entry)
    const d = join(dst, entry)
    if (statSync(s).isDirectory()) {
      count += copyDirRecursive(s, d)
    } else {
      copyFileSync(s, d)
      count++
    }
  }
  return count
}

function stripFrontmatter(md: string): string {
  if (!md.startsWith("---\n")) return md
  const end = md.indexOf("\n---\n", 4)
  if (end === -1) return md
  return md.slice(end + 5).trimStart()
}

function buildGeminiMd(skillSrcRoot: string): string {
  const TICKERCODE_BLOCK_START = "<!-- tickercode-skills-start -->"
  const TICKERCODE_BLOCK_END = "<!-- tickercode-skills-end -->"
  const intro = `${TICKERCODE_BLOCK_START}

# Tickercode Skills (auto-generated by \`tc setup gemini\`)

ticker-code.com の MCP server (\`mcp__tickercode__*\`) と組み合わせて使う指南書群。
ユーザーが日本株の銘柄やテーマについて尋ねた時、以下の方針で対応してください。

`
  const sections: string[] = [intro]
  for (const name of SKILL_NAMES) {
    const path = join(skillSrcRoot, name, "SKILL.md")
    if (!existsSync(path)) continue
    const body = stripFrontmatter(readFileSync(path, "utf8"))
    sections.push(`\n---\n\n## Skill: ${name}\n\n${body.trim()}\n`)
  }
  sections.push(`\n${TICKERCODE_BLOCK_END}\n`)
  return sections.join("")
}

function upsertGeminiMd(geminiMdPath: string, generated: string): "created" | "updated" | "appended" {
  const TICKERCODE_BLOCK_START = "<!-- tickercode-skills-start -->"
  const TICKERCODE_BLOCK_END = "<!-- tickercode-skills-end -->"
  const dir = dirname(geminiMdPath)
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
  if (!existsSync(geminiMdPath)) {
    writeFileSync(geminiMdPath, generated, "utf8")
    return "created"
  }
  const existing = readFileSync(geminiMdPath, "utf8")
  if (
    existing.includes(TICKERCODE_BLOCK_START) &&
    existing.includes(TICKERCODE_BLOCK_END)
  ) {
    const before = existing.slice(0, existing.indexOf(TICKERCODE_BLOCK_START))
    const after = existing.slice(
      existing.indexOf(TICKERCODE_BLOCK_END) + TICKERCODE_BLOCK_END.length,
    )
    writeFileSync(geminiMdPath, before + generated + after, "utf8")
    return "updated"
  }
  const sep =
    existing && !existing.endsWith("\n\n")
      ? existing.endsWith("\n")
        ? "\n"
        : "\n\n"
      : ""
  writeFileSync(geminiMdPath, existing + sep + generated, "utf8")
  return "appended"
}

function upsertJsonMcpServer(
  settingsPath: string,
  serverName: string,
  serverConfig: Record<string, unknown>,
  force: boolean,
): "created" | "updated" | "skipped" | "added" {
  const dir = dirname(settingsPath)
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
  let parsed: Record<string, unknown> = {}
  if (existsSync(settingsPath)) {
    try {
      const raw = readFileSync(settingsPath, "utf8").trim()
      parsed = raw ? (JSON.parse(raw) as Record<string, unknown>) : {}
    } catch (err) {
      throw new Error(
        `${settingsPath} のパースに失敗しました: ${(err as Error).message}`,
      )
    }
  }
  const mcpServers =
    (parsed.mcpServers as Record<string, unknown> | undefined) ?? {}
  const existed = serverName in mcpServers
  if (existed && !force) return "skipped"
  mcpServers[serverName] = serverConfig
  parsed.mcpServers = mcpServers
  writeFileSync(settingsPath, JSON.stringify(parsed, null, 2) + "\n", "utf8")
  if (!existsSync(settingsPath)) return "created"
  return existed ? "updated" : "added"
}

const codexCommand = defineCommand({
  meta: {
    name: "codex",
    description: "Setup tickercode skills + MCP server for Codex CLI",
  },
  args: {
    "skills-dir": {
      type: "string",
      description: "Where to copy skill bundles (default: ~/.agents/skills)",
    },
    "config-path": {
      type: "string",
      description: "Codex config TOML path (default: ~/.codex/config.toml)",
    },
    force: {
      type: "boolean",
      description: "Overwrite existing [mcp_servers.tickercode] section",
      default: false,
    },
  },
  async run({ args }) {
    const skillsDir = args["skills-dir"]
      ? String(args["skills-dir"])
      : join(homedir(), ".agents", "skills")
    const configPath = args["config-path"]
      ? String(args["config-path"])
      : join(homedir(), ".codex", "config.toml")

    process.stdout.write(pc.bold("Setting up tickercode for Codex CLI…\n"))

    // 1. config.toml: append [mcp_servers.tickercode]
    const configDir = dirname(configPath)
    if (!existsSync(configDir)) mkdirSync(configDir, { recursive: true })
    const existingToml = existsSync(configPath)
      ? readFileSync(configPath, "utf8")
      : ""
    const hasSection = existingToml.includes("[mcp_servers.tickercode]")
    if (hasSection && !args.force) {
      process.stdout.write(
        pc.dim(`  - ${configPath} に既存、skip（--force で上書き）\n`),
      )
    } else if (hasSection && args.force) {
      const replaced = existingToml.replace(
        /\[mcp_servers\.tickercode\][\s\S]*?(?=\n\[|\Z)/,
        `${TOML_SECTION}\n`,
      )
      writeFileSync(configPath, replaced, "utf8")
      process.stdout.write(`  ${pc.green("✓")} ${configPath} の既存セクションを更新\n`)
    } else {
      const sep =
        existingToml && !existingToml.endsWith("\n\n")
          ? existingToml.endsWith("\n")
            ? "\n"
            : "\n\n"
          : ""
      const newToml = existingToml + sep + TOML_SECTION + "\n"
      writeFileSync(configPath, newToml, "utf8")
      process.stdout.write(
        `  ${pc.green("✓")} ${configPath} に MCP server 設定を追記\n`,
      )
    }

    // 2. Copy skills to ~/.agents/skills/
    const skillSrcRoot = getSkillSourceRoot()
    let totalCopied = 0
    for (const name of SKILL_NAMES) {
      const src = join(skillSrcRoot, name)
      const dst = join(skillsDir, name)
      if (!existsSync(src)) {
        process.stdout.write(pc.dim(`  - ${name}: source not found, skip\n`))
        continue
      }
      const n = copyDirRecursive(src, dst)
      totalCopied += n
      process.stdout.write(
        `  ${pc.green("✓")} ${name} → ${dst} (${n} files)\n`,
      )
    }

    process.stdout.write(`\n${pc.bold("完了")}: ${totalCopied} files copied\n`)
    process.stdout.write(
      pc.dim(`  - tc auth login（未実行なら）で API key を設定\n`),
    )
    process.stdout.write(
      pc.dim(`  - codex を起動し「6594 のディスカッション」と打ってみる\n`),
    )
  },
})

const geminiCommand = defineCommand({
  meta: {
    name: "gemini",
    description: "Setup tickercode MCP + GEMINI.md for Gemini CLI",
  },
  args: {
    "settings-path": {
      type: "string",
      description: "Gemini settings.json path (default: ~/.gemini/settings.json)",
    },
    "gemini-md-path": {
      type: "string",
      description: "GEMINI.md path (default: ~/.gemini/GEMINI.md)",
    },
    force: {
      type: "boolean",
      description: "Overwrite existing tickercode entry / GEMINI.md block",
      default: false,
    },
  },
  async run({ args }) {
    const settingsPath = args["settings-path"]
      ? String(args["settings-path"])
      : join(homedir(), ".gemini", "settings.json")
    const geminiMdPath = args["gemini-md-path"]
      ? String(args["gemini-md-path"])
      : join(homedir(), ".gemini", "GEMINI.md")

    process.stdout.write(pc.bold("Setting up tickercode for Gemini CLI…\n"))

    // 1. settings.json: upsert mcpServers.tickercode
    const action = upsertJsonMcpServer(
      settingsPath,
      "tickercode",
      {
        command: "tc",
        args: ["mcp"],
        env: { TICKERCODE_API_KEY: "$TICKERCODE_API_KEY" },
      },
      Boolean(args.force),
    )
    if (action === "skipped") {
      process.stdout.write(
        pc.dim(`  - ${settingsPath} に既存、skip（--force で上書き）\n`),
      )
    } else {
      const verb =
        action === "updated" ? "の既存エントリを更新" : "に MCP server 設定を追記"
      process.stdout.write(`  ${pc.green("✓")} ${settingsPath} ${verb}\n`)
    }

    // 2. GEMINI.md: flatten skill content into single instruction file
    const skillSrcRoot = getSkillSourceRoot()
    const generated = buildGeminiMd(skillSrcRoot)
    const mdAction = upsertGeminiMd(geminiMdPath, generated)
    const mdVerb =
      mdAction === "created"
        ? "を新規作成"
        : mdAction === "updated"
          ? "の tickercode ブロックを更新"
          : "に tickercode ブロックを追記"
    process.stdout.write(`  ${pc.green("✓")} ${geminiMdPath} ${mdVerb}\n`)

    process.stdout.write(`\n${pc.bold("完了")}\n`)
    process.stdout.write(
      pc.dim(`  - tc auth login（未実行なら）で API key を設定\n`),
    )
    process.stdout.write(
      pc.dim(`  - gemini を起動し「6594 のディスカッション」と打ってみる\n`),
    )
  },
})

export const setupCommand = defineCommand({
  meta: {
    name: "setup",
    description: "Setup tickercode for various CLI clients (codex / gemini)",
  },
  subCommands: {
    codex: codexCommand,
    gemini: geminiCommand,
  },
})
